name: "My Service Proxy"
version: "1.2"
slug: "my_service_proxy"
url: "https://github.com/ItsGers8/hass-addons/service-proxy"
description: "Proxy for my local service running on localhost:9443"
startup: "application"
ingress: true
ingress_port: 9443
panel_icon: "mdi:server"
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
ports: {}
map:
  - config:rw
