name: "Portainer"
version: "1.3.5"
url: "https://github.com/ItsGers8/hass-addons/tree/main/service-proxy"
ingress: true
panel_icon: "mdi:docker"
init: false
slug: "portainer"
description: "Ingress testing"
arch:
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
