name: "My Service Proxy"
version: "1.2.7"
slug: "my_service_proxy"
url: "https://github.com/ItsGers8/hass-addons/tree/main/service-proxy"
description: "Proxy for my local service running on localhost:9443"
startup: "application"
ingress: true
ingress_port: 9443
panel_icon: "mdi:server"
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
ports:
  8080: 8080
  443: 443
map:
  - config:rw
